
FROM node:20.19.2-bullseye

RUN apt-get update && \
    apt-get install -y \
    git \
    python3 \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm turbo
